### ISSUE TITLE
Breaking changes with most recent version of puppeteer

### ISSUE THREAD

**Issue by yaakov123** [jumpalottahigh/youtube-timestamp-screenshot#1]
First off, awesome repo. Great job. I just want to make everyone aware that the code here does not work with the latest version of puppeteer. Just a heads up, not really an issue (although the older version of puppeteer has some security vulnerabilities)

**Comment by jumpalottahigh** [comment]
@yaakov123 Thanks so much for the feedback, will plan some time to update this project.

**Comment by jumpalottahigh** [comment]
Updated the dependencies, all seem to be fine with the app (check out the latest production version here: https://youtube-screenshot.netlify.com/).

**Comment by yaakov123** [comment]
I just checked and the result is, the screenshot that is generated is the regular youtube video thumbnail with the play button visible. I noticed that if you run puppeteer in "headfull" mode it works somewhat fine (There is still some white borders) For now, I'll stay with the older version of puppeteer.
